with source_data as (
    {{ raw_parquet_union('yf_fundamentals.parquet') }}
),

renamed as (
    select
        cast(s.market_code as varchar) as market_code,
        cast(s.ticker as varchar) as ticker,
        cast(s.snapshot_date as date) as snapshot_date,
        cast(s.info_forward_pe as double) as info_forward_pe,
        cast(s.info_operating_margins as double) as info_operating_margins,
        cast(s.info_revenue_growth as double) as info_revenue_growth,
        cast(s.info_net_debt as double) as info_net_debt,
        cast(s.info_total_debt as double) as info_total_debt,
        cast(s.info_total_cash as double) as info_total_cash,
        cast(s.info_ebitda as double) as info_ebitda,
        cast(s.info_return_on_equity as double) as info_return_on_equity,
        cast(s.info_current_ratio as double) as info_current_ratio,
        cast(s.info_price_to_book as double) as info_price_to_book,
        cast(s.info_price_to_sales as double) as info_price_to_sales,
        cast(s.info_ev_to_ebitda as double) as info_ev_to_ebitda,
        cast(s.info_free_cashflow as double) as info_free_cashflow,
        cast(s.info_market_cap as double) as info_market_cap,
        cast(s.info_sector as varchar) as info_sector,
        cast(s.info_currency as varchar) as info_currency,
        cast(s.info_long_name as varchar) as info_long_name,
        cast(s.info_business_summary as varchar) as info_business_summary,
        cast(s.info_founded_year as bigint) as info_founded_year,
        cast(s.stmt_total_revenue as double) as stmt_total_revenue,
        cast(s.stmt_free_cash_flow as double) as stmt_free_cash_flow,
        cast(s.stmt_fiscal_period_end as date) as stmt_fiscal_period_end,
        cast(s.stmt_currency as varchar) as stmt_currency,
        cast(s.qtr_operating_income_0 as double) as qtr_operating_income_0,
        cast(s.qtr_operating_income_1 as double) as qtr_operating_income_1,
        cast(s.qtr_operating_income_2 as double) as qtr_operating_income_2,
        cast(s.qtr_operating_income_3 as double) as qtr_operating_income_3,
        cast(s.qtr_total_revenue_0 as double) as qtr_total_revenue_0,
        cast(s.qtr_total_revenue_1 as double) as qtr_total_revenue_1,
        cast(s.qtr_total_revenue_2 as double) as qtr_total_revenue_2,
        cast(s.qtr_total_revenue_3 as double) as qtr_total_revenue_3,
        cast(s.qtr_operating_revenue_0 as double) as qtr_operating_revenue_0,
        cast(s.qtr_operating_revenue_1 as double) as qtr_operating_revenue_1,
        cast(s.qtr_operating_revenue_2 as double) as qtr_operating_revenue_2,
        cast(s.qtr_operating_revenue_3 as double) as qtr_operating_revenue_3,
        cast(s.qtr_operating_expense_0 as double) as qtr_operating_expense_0,
        cast(s.qtr_operating_expense_1 as double) as qtr_operating_expense_1,
        cast(s.qtr_operating_expense_2 as double) as qtr_operating_expense_2,
        cast(s.qtr_operating_expense_3 as double) as qtr_operating_expense_3,
        cast(s.stmt_operating_income as double) as stmt_operating_income,
        cast(s.stmt_operating_revenue as double) as stmt_operating_revenue,
        cast(s.stmt_operating_expense as double) as stmt_operating_expense,
        cast(s.stmt_stockholders_equity as double) as stmt_stockholders_equity,
        cast(s.stmt_total_debt as double) as stmt_total_debt,
        cast(s.stmt_current_assets as double) as stmt_current_assets,
        cast(s.stmt_current_liabilities as double) as stmt_current_liabilities,
        cast(s.stmt_cash_and_equivalents as double) as stmt_cash_and_equivalents,
        cast(s.stmt_tangible_book_value as double) as stmt_tangible_book_value
    from source_data as s
)

select * from renamed
