#!/usr/bin/env python3
"""Render docs/data_contract.md's card-metrics table from the metric_catalogue seed.

The seed (dbt_analytics/seeds/metric_catalogue.csv) is the single source of truth for every
card metric. The data contract used to restate each formula by hand and drifted from the seed;
now the block between the two marker comments is written by this script and a test refuses a
stale block, the same lock frontend/metrics.json has.

    python scripts/render_metric_table.py          # rewrite the block in place
    python scripts/render_metric_table.py --check  # exit 1 if the committed block is stale
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SEED_PATH = REPO_ROOT / "dbt_analytics" / "seeds" / "metric_catalogue.csv"
DOC_PATH = REPO_ROOT / "docs" / "data_contract.md"
START = "<!-- metric_table:start (generated by scripts/render_metric_table.py, do not edit) -->"
END = "<!-- metric_table:end -->"


def _cell(text: str) -> str:
    return (text or "").strip().replace("|", "\\|")


def _formula(row: dict[str, str]) -> str:
    numerator = _cell(row["numerator_expr"])
    denominator = _cell(row["denominator_expr"])
    if denominator:
        return f"`({numerator}) / ({denominator})`"
    return f"`{numerator}`"


def render_table(seed_path: Path = SEED_PATH) -> str:
    with seed_path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    lines = [
        "| Card metric | Label | Shown for | Formula spec, over `" + _cell(rows[0]["base_relation"]) + "` | Format | Direction |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| `{id}` | {label} | {types} | {formula} | `{fmt}` | {direction} |".format(
                id=_cell(row["metric_id"]),
                label=_cell(row["label"]),
                types=", ".join(_cell(t) for t in row["applies_to"].split("|") if t.strip()),
                formula=_formula(row),
                fmt=_cell(row["format"]),
                direction=_cell(row["direction"]).replace("_", " "),
            )
        )
    return "\n".join(lines)


def _split(doc: str) -> tuple[str, str, str]:
    start = doc.index(START) + len(START)
    end = doc.index(END)
    return doc[:start], doc[start:end], doc[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the block is stale")
    args = parser.parse_args(argv)

    with DOC_PATH.open(encoding="utf-8", newline="") as handle:
        doc = handle.read()
    try:
        head, current, tail = _split(doc)
    except ValueError:
        print(f"render_metric_table: markers not found in {DOC_PATH}", file=sys.stderr)
        return 1
    newline = "\r\n" if "\r\n" in doc else "\n"
    fresh = newline + render_table().replace("\n", newline) + newline
    if current == fresh:
        print("render_metric_table: block is current")
        return 0
    if args.check:
        print(
            "render_metric_table: docs/data_contract.md's metric table is stale; "
            "run python scripts/render_metric_table.py",
            file=sys.stderr,
        )
        return 1
    with DOC_PATH.open("w", encoding="utf-8", newline="") as handle:
        handle.write(head + fresh + tail)
    print("render_metric_table: block rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
